// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuyPnCGvy3Sz8Xaf_SltYw4KS4YmnJVLc',
    appId: '1:880993472607:web:940c1eba38d36998238bea',
    messagingSenderId: '880993472607',
    projectId: 'ecommerce-14963',
    authDomain: 'ecommerce-14963.firebaseapp.com',
    storageBucket: 'ecommerce-14963.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9hQwXrsvBQdiQA2Fxs9o04GO0hHkqRc',
    appId: '1:880993472607:android:3c86dc4725c580df238bea',
    messagingSenderId: '880993472607',
    projectId: 'ecommerce-14963',
    storageBucket: 'ecommerce-14963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEAIqWyjEbyY9r5JaOjMTUcrQ2QL4XBD8',
    appId: '1:880993472607:ios:41daf62ec4accf6e238bea',
    messagingSenderId: '880993472607',
    projectId: 'ecommerce-14963',
    storageBucket: 'ecommerce-14963.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEAIqWyjEbyY9r5JaOjMTUcrQ2QL4XBD8',
    appId: '1:880993472607:ios:41daf62ec4accf6e238bea',
    messagingSenderId: '880993472607',
    projectId: 'ecommerce-14963',
    storageBucket: 'ecommerce-14963.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuyPnCGvy3Sz8Xaf_SltYw4KS4YmnJVLc',
    appId: '1:880993472607:web:5827036615f4d357238bea',
    messagingSenderId: '880993472607',
    projectId: 'ecommerce-14963',
    authDomain: 'ecommerce-14963.firebaseapp.com',
    storageBucket: 'ecommerce-14963.appspot.com',
  );
}
